GET http://localhost:3000/movies/

###
POST http://localhost:3000/movies/
Content-Type: application/json
 
{
    "director_id":6,
    "movie_name":"Jurassic Park",
    "lead_nctor":"Jeff Goldblum"
}
###
GET http://localhost:3000/movies/12/

###
PUT http://localhost:3000/movies/24/
Content-Type: application/json

{
    "directorId":24,
    "movieName":"Thor",
    "leadActor":"Christopher Hemsworth"
}

###
DELETE http://localhost:3000/movies/123/

###
GET http://localhost:3000/directors/

###
GET http://localhost:3000/directors/4/movie/